# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff
        args:
          - --fix
          - --line-length=120
          - --show-source
        files: ^backend/.*\.py$
        exclude: ^backend/alembic/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.20.0
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
          - --show-error-codes
          - --follow-imports=silent
        additional_dependencies:
          - mypy==1.20.0
        files: ^backend/.*\.py$
        exclude: ^backend/alembic/

  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
        args:
          - --profile
          - black
        files: ^backend/.*\.py$
